org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true

# Force Gradle to use Android Studio bundled JDK
org.gradle.java.home=G:\\Android Studio\\jbr

# Flutter template flags
android.newDsl=false
android.builtInKotlin=false

# Avoid Kotlin incremental cache path issue on Windows multi-drive setup
kotlin.incremental=false