// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgI4aCkb2-GO1vAVy_nCRIgs6Q_9HSFQ',
    appId: '1:70130518176:web:5fdc883f173dbc22d6e1c5',
    messagingSenderId: '70130518176',
    projectId: 'meditwin-ai-5b3c3',
    authDomain: 'meditwin-ai-5b3c3.firebaseapp.com',
    storageBucket: 'meditwin-ai-5b3c3.firebasestorage.app',
    measurementId: 'G-05YCC0ZX1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADL_zb_BJm11VO5uB9RjF8EOFytyLazsA',
    appId: '1:70130518176:android:eb1b501f0439acfdd6e1c5',
    messagingSenderId: '70130518176',
    projectId: 'meditwin-ai-5b3c3',
    storageBucket: 'meditwin-ai-5b3c3.firebasestorage.app',
  );
}
